style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/sengelha/latex-scripts
options:
  commits:
    filters:
      Type:
        - chg
        - fix
        - new
  commit_groups:
    title_maps:
      new: New Features
      fix: Buf Fixes
      chg: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE